name: Spigot Build

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get_versions.outputs.versions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch versions to build and generate README.md
        id: get_versions
        run: |
          chmod +x FETCH.sh
          ./FETCH.sh

      - name: Upload README.md to release
        uses: softprops/action-gh-release@v2
        with:
          name: Spigot
          tag_name: Spigot
          body_path: README.md

      - name: Push builds to release branch
        run: |
          (echo -e "# Spigot Build\n\nThis project provides an automated build of Spigot Minecraft Server, scheduled to build every days.\n\nThe latest build is available in [release](https://github.com/doandat943/spigot-build/releases/latest).\n\n"; cat README.md) > temp_file && mv temp_file README.md
          git config user.name "github-actions"
          git config user.email "41898282+github-actions@users.noreply.github.com"
          git add README.md
          git commit -m "Update ${{ env.date }} to latest build"
          git push

  build:
    runs-on: ubuntu-latest
    needs: get-versions
    strategy:
      matrix:
        version: ${{ fromJSON(needs.get-versions.outputs.versions) }}

    steps:
      - name: Set environment variable
        run: |
          java=$(curl -L -s "https://hub.spigotmc.org/versions/${{ matrix.version }}.json" | jq -r '.javaVersions[0]')
          if [ "$java" == "null" ]; then
            java=8
          else
            java=$((java - 44))
          fi

          echo "java=$java" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java }}
          distribution: "temurin"

      - name: Set up BuildTool
        run: |
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
          mkdir -p output

      - name: Build Spigot version
        run: |
          java -jar BuildTools.jar --rev "${{ matrix.version }}" --output-dir output

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Spigot
          tag_name: Spigot
          files: output/*.jar
