name: Spigot Build

on:
  schedule:
    - cron: "0 0 */4 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get-versions.outputs.versions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch versions
        id: get-versions
        run: |
          versions=[$(curl -L -s https://joverse.us/spigot | grep -oP '(?<=href=")[^"]*' | grep -E '^[0-9]+\.[0-9]+(\.[0-9]+)?' | grep -v '-' | sed 's/.json//' | sort -V | paste -sd ',')]
          echo "::set-output name=versions::${versions}"

      - name: Generate README.md
        run: |
          chmod +x README.sh
          ./README.sh

  build:
    runs-on: ubuntu-latest
    needs: get-versions
    strategy:
      matrix:
        version: ${{ needs.get-versions.outputs.versions }}

    steps:

      - name: Set environment variable
        run: |
          echo "date=$(date +%Y.%m.%d)" >> $GITHUB_ENV
          IFS='.' read -r major minor patch <<<"${{ matrix.version }}"
      
          if ((major == 1 && minor < 17)); then
              echo "java=11" >> $GITHUB_ENV
          elif ((major == 1 && minor >= 17 && minor < 20)); then
              echo "java=17" >> $GITHUB_ENV
          elif ((major == 1 && minor >= 20)); then
              echo "java=21" >> $GITHUB_ENV
          fi
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java }}
          distribution: "temurin"
      
      - name: Restore cache .m2 folder
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-cache-maven-${{ env.date }}
          restore-keys: ${{ runner.os }}-cache-maven-

      - name: Restore cache Spigot repos
        uses: actions/cache/restore@v4
        with:
          path: |
            apache-maven-*
            Bukkit
            CraftBukkit
            Spigot
          key: ${{ runner.os }}-cache-spigot-${{ env.date }}
          restore-keys: ${{ runner.os }}-cache-spigot-

      - name: Restore cache build works
        uses: actions/cache/restore@v4
        with:
          path: work
          key: ${{ runner.os }}-cache-build-work-${{ env.date }}
          restore-keys: ${{ runner.os }}-cache-build-work-

      - name: Set up BuildTool
        run: |
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
          mkdir -p output
          chmod +x ./build.sh

      - name: Build Spigot version
        run: |
          java -jar BuildTools.jar --rev "${{ matrix.version }}" --output-dir output

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.date }}
          tag_name: ${{ env.date }}
          files: output/*.jar
          body_path: output/README.md

      - name: Save cache .m2 folder
        uses: actions/cache/save@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-cache-maven-${{ env.date }}

      - name: Save cache Spigot repos
        uses: actions/cache/save@v4
        with:
          path: |
            apache-maven-*
            Bukkit
            CraftBukkit
            Spigot
          key: ${{ runner.os }}-cache-spigot-${{ env.date }}

      - name: Save cache build works
        uses: actions/cache/save@v4
        with:
          path: work
          key: ${{ runner.os }}-cache-build-work-${{ env.date }}
