name: Spigot Build

on:
  schedule:
    - cron: '0 0 */4 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: buildtool
        
    - name: Set environment variable
      run: |
        echo "date=$(date +%Y.%m.%d)" >> $GITHUB_ENV
      
    - name: Restore cache .m2 folder
      uses: actions/cache/restore@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-cache-maven-${{ env.date }}
        restore-keys: ${{ runner.os }}-cache-maven-
        
    - name: Restore cache Spigot repos
      uses: actions/cache/restore@v4
      with:
        path: |
          buildtool/apache-maven-*
          buildtool/Bukkit
          buildtool/CraftBukkit
          buildtool/Spigot
        key: ${{ runner.os }}-cache-spigot-${{ env.date }}
        restore-keys: ${{ runner.os }}-cache-spigot-
        
    - name: Restore cache build works
      uses: actions/cache/restore@v4
      with:
        path: buildtool/work
        key: ${{ runner.os }}-cache-build-work-${{ env.date }}
        restore-keys: ${{ runner.os }}-cache-build-work-
        
    - name: Set up BuildTool
      run: |
        wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
        mkdir -p output
        cat /home/runner/work/_temp/*.sh
      working-directory: buildtool
        
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Build Spigot version with Java 21
      run: ./build.sh JAVA21
      working-directory: buildtool
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build Spigot version with Java 17
      run: ./build.sh JAVA17
      working-directory: buildtool
      
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Build Spigot version with Java 8
      run: ./build.sh JAVA8
      working-directory: buildtool
      
    - name: Copy build output
      run: mkdir -p release && mv buildtool/output/*.jar release/
      
    - name: Generate readme
      run: ./generate_version_table.sh ${{ env.date }} README.md
      working-directory: release
      
    - name: Push builds to release branch
      run: |
        git init
        git config user.name "github-actions"
        git config user.email "41898282+github-actions@users.noreply.github.com"
        git remote add origin "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}"
        git checkout -b release
        git add README.md
        git commit -m "${{ env.date }}"
        git push -f origin release
      working-directory: release
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ env.date }}
        tag_name: ${{ env.date }}
        target_commitish: release
        files: release/*.jar
        body_path: release/README.md
        
    - name: Save cache .m2 folder
      uses: actions/cache/save@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-cache-maven-${{ env.date }}
        
    - name: Save cache Spigot repos
      uses: actions/cache/save@v4
      with:
        path: |
          buildtool/apache-maven-*
          buildtool/Bukkit
          buildtool/CraftBukkit
          buildtool/Spigot
        key: ${{ runner.os }}-cache-spigot-${{ env.date }}
        
    - name: Save cache build works
      uses: actions/cache/save@v4
      with:
        path: buildtool/work
        key: ${{ runner.os }}-cache-build-work-${{ env.date }}